### ISSUE TITLE
Using Spotter.grab_data() fails when attempting to get data from a Spotter you don't own but have access to

### ISSUE THREAD

**Issue by g-mo** [sofarocean/sofar-api-client-python#14]
The return payload from grab_data() is expected to have a `limit` key in it but it doesn't when you don't own the Spotter you're accessing. When this happens, this [line](https://github.com/sofarocean/sofar-api-client-python/blob/master/src/pysofar/sofar.py#L586) triggers a `KeyError`

**Comment by tcj** [comment]
Ran into this today.  Thanks for the pointer @g-mo.

What thoughts do you have on a potential resolution?  

- A more specific error message (perhaps wrapped in a `try`/`except`)?
- Making a `limit` key present in these situations
- Making the client gracefully handle situation where `limit` isn't present
- etc.

**Comment by tcj** [comment]
https://github.com/sofarocean/sofar-api-client-python/blob/e93ff9e97867a620345fa8d590b8dcf048d0e4ae/src/pysofar/sofar.py#L587-L597

The line in question sets a variable that is only being used by a line that is commented out.  This line sets `lim`:

`            lim = _query['limit']`

and/but it looks like `lim` is only being used here:

`                # len(results) < lim`

So might it be possible to also comment out the line that sets `lim` as a possible way to resolve this issue?

**Comment by tcj** [comment]
Confirmed, commenting out this line allows client to advance with no further tracebacks.

https://github.com/sofarocean/sofar-api-client-python/blob/e93ff9e97867a620345fa8d590b8dcf048d0e4ae/src/pysofar/sofar.py#L586

**Comment by tcj** [comment]
This was still happening to me today, even while on pysofar 0.1.13.  May need to look into this.
