### ISSUE TITLE
Curl error when accessing history data

### ISSUE THREAD

**Issue by slowtoaccept** [sofarocean/sofar-api-client-python#19]
curl -o spot-0222-hist.json https://api.sofarocean.com/api/wave-data?spotterId=SPOT-0222&limit=20 -H "token: ******3665"
yields the following response:

'limit' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tcj** [comment]
Hello!  This will likely be addressed by enclosing the URL in single- or double-quotes, like this:

`"https://api.sofarocean.com/api/wave-data?spotterId=SPOT-0222&limit=20"`

Without the quotes, your computer's shell is attempting to interpret the ampersand, instead of passing it along to `curl`.

**Comment by slowtoaccept** [comment]
thx. wks.
